languageCode = "en-us"
title = "fromAtoB Engineering"
baseurl = "https://eng.fromatob.com/"
theme = "fromAtoB"

[Author]
  github = "fromAtoB"
  twitter = "fromatob_eng"

[permalinks]
  post = "/post/:year/:month/:title/"
